version: '3'

services:
  db:
    container_name: 'healthy-knowledge-db'
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Ulaanbaatar'
    networks:
      - net2
    ports:
      - 3308:3306
networks:
  net2:
